name: prnet-tf2
channels:
  - conda-forge

dependencies:
  - python==3.7
  - pip
  - pip:
    - tensorflow-gpu==2.0.0
    - torch
    - opencv-python
    - scikit-image
    - PyYAML
    - tqdm
    - Pillow
